# Site settings
title: Refugee Ed Tech Solutions
email: updates@refugeeedtechsolutions.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://refugeeedtechsolutions.org" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

exclude: [vendor, 'Gemfile', 'Gemfile.lock', 'Readme.md']
